- name: Check multi-arch support
  ansible.builtin.command:
    cmd: dpkg --print-foreign-architectures
  register: dpkg_archs
  changed_when: false
- name: Enable multi-arch support
  ansible.builtin.command:
    cmd: dpkg --add-architecture i386
  when: "'i386' not in dpkg_archs.stdout_lines"
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
